### PR TITLE
feat: validate admission encounter to check if encounter already duplicated before scheduling admission

### PR DESCRIPTION
**Pull request by av-dev2**

### CODE REVIEW

**Comment by av-dev2** [comment]
Rock: HMS TZ: #20

**Review by aakvatech — CHANGES_REQUESTED** [review]
Add frm refresh as well on JS so that the form reloads

**Comment by aakvatech** [comment]
LGTM

**Comment by aakvatech** [comment]
@av-dev2 should we have mergify trigger this to the correct branches?

**Pull request merged**
